apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cosign-sign
spec:
  params:
  - name: image
    description: The image to sign.
    type: string
  - name: cosign-image
    description: The image with cosign in it that you want to run this Task in.
    default: gcr.io/projectsigstore/cosign:1.3.0
    type: string

  workspaces:
  - name: key
    description: Use a secret containing 1) An entry named "cosign.key" with the private key that will be used to sign the image and 2) An entry named "password" with the password for the key.

  steps:
  - name: sign
    image: $(params.cosign-image)
    command: ["/bin/bash", "-c"]
    env:
    - name: IMAGE
      value: $(params.image)
    args:
    - |-
      echo foo
      #cosign sign --key /workspaces/key/$(private-key-filename) $(params.image)

