apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: markdown-report
spec:
  params:
    - name: git-clone-url
      type: string
    - name: git-clone-commit
      type: string
    - name: build-image-image-digest
      type: string
  steps:
    - name: report
      image: registry.access.redhat.com/ubi9-minimal
      command: ["/bin/bash", "-c"]
      args:
        - |-
          cat << EOF | tee report.md
          # Pipeline Report
          
          ## Git Clone
          | Name | Value |
          | ----------- | ----------- |
          | url | $(params.git-clone-url) |
          | commit | $(params.git-clone-commit) |

          ## Build Image
          | Name | Value |
          | ----------- | ----------- |
          | IMAGE_DIGEST | $(params.build-image-image-digest) |

          ## Deploy: DEV
          | Name          | Value |
          |---------------| ----------- |
          | Chart URL     | TBD |
          | Chart Version | TBD |
          | Deployed URL | TBD |
          EOF

