apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: markdown-report
spec:
  params:
    - name: pipeline-param-deployment-name
      type: string
    - name: pipeline-param-git-url
      type: string
    - name: pipeline-param-git-revision
      type: string
    - name: pipeline-param-IMAGE
      type: string
    - name: pipeline-param-TLSVERIFY
      type: string

    - name: git-clone-params-url
      type: string
    - name: git-clone-params-subdirectory
      type: string
    - name: git-clone-params-revision
      type: string
    - name: git-clone-results-commit
      type: string
    - name: git-clone-results-url
      type: string

    - name: build-image-params-IMAGE
      type: string
    - name: build-image-params-TLSVERIFY
      type: string
    - name: build-image-results-IMAGE_DIGEST
      type: string

    - name: deploy-dev-params-charts_dir
      type: string
    - name: deploy-dev-params-overwrite_values
      type: string

  steps:
    - name: report
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      command: ["/bin/bash", "-c"]

      env:
      - name: PIPELINE_PARAM_DEPLOYMENT_NAME
        value: $(params.pipeline-param-deployment-name)
      - name: PIPELINE_PARAM_GIT_URL
        value: $(params.pipeline-param-git-url)
      - name: PIPELINE_PARAM_GIT_REVISION
        value: $(params.pipeline-param-git-revision)
      - name: PIPELINE_PARAM_IMAGE
        value: $(params.pipeline-param-IMAGE)
      - name: PIPELINE_PARAM_TLSVERIFY
        value: $(params.pipeline-param-TLSVERIFY)


      - name: GIT_CLONE_PARAMS_URL
        value: $(params.git-clone-params-url)
      - name: GIT-CLONE-PARAMS-SUBDIRECTORY
        value: $(params.git-clone-params-subdirectory)
      - name: GIT_CLONE_PARAMS_REVISION
        value: $(params.git-clone-params-revision)
      - name: GIT_CLONE_RESULTS_COMMIT
        value: $(params.git-clone-results-commit)
      - name: GIT_CLONE_RESULTS_URL
        value: $(params.git-clone-results-url)
  
      - name: BUILD_IMAGE_PARAMS_IMAGE
        value: $(params.build-image-params-IMAGE)
      - name: BUILD_IMAGE_PARAMS_TLSVERIFY
        value: $(params.build-image-params-TLSVERIFY)
      - name: BUILD_IMAGE_RESULTS_IMAGE_DIGEST
        value: $(params.build-image-results-IMAGE_DIGEST)
  
      - name: DEPLOY_DEV_PARAMS_CHARTS_DIR
        value: $(params.deploy-dev-params-charts_dir)
      - name: DEPLOY_DEV_PARAMS_OVERWRITE_VALUES
        value: $(params.deploy-dev-params-overwrite_values)

      args:
        - |-
          DEPLOY_DEV_FACTS_ROUTE_NAME=`oc get route -o name | sort | head -n 1`
          DEPLOY_DEV_FACTS_ROUTE_URL=https://`oc get ${DEPLOY_DEV_FACTS_ROUTE_NAME} -o jsonpath='{.spec.host}'`/

          cat << EOF
          # Pipeline Report
          
          ## Pipeline Params
          | Name         | Value                          |
          | ------------ | ------------------------------ |
          | Deployment Name | ${PIPELINE_PARAM_DEPLOYMENT_NAME} |
          | Git URL         | ${PIPELINE_PARAM_GIT_URL} |
          | Git Revision    | ${PIPELINE_PARAM_GIT_REVISION} |
          | Image           | ${PIPELINE_PARAM_IMAGE} |
          | TLS Verify      | ${PIPELINE_PARAM_TLSVERIFY} |


          ## Task Results - Git Clone
          | Name         | Value                          |
          | ------------ | ------------------------------ |
          | URL          | ${GIT_CLONE_RESULTS_URL} |
          | Commit       | ${GIT_CLONE_RESULTS_COMMIT} |
 
          ## Task Results - Build Image
          | Name         | Value                          |
          | ------------ | ------------------------------ |
          | Image Digest | ${BUILD_IMAGE_RESULTS_IMAGE_DIGEST} |

          ## Task Results - Deploy: DEV
          | Name         | Value                          |
          |------------- | ------------------------------ |
          | Route Name   | ${DEPLOY_DEV_FACTS_ROUTE_NAME} |
          | Route URL    | ${DEPLOY_DEV_FACTS_ROUTE_URL} |
          EOF

