apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: markdown-report
spec:
  params:
    - name: git-clone-url
      type: string
    - name: git-clone-commit
      type: string
    - name: build-image-image-digest
      type: string
  steps:
    - name: report
      image: registry.access.redhat.com/ubi9-minimal
      command: ["/bin/bash", "-c"]
      args:
        - |-
          cat << EOF | tee report.md
          # Pipeline Report
          
          ## Git Clone
          | Name | Value |
          | ----------- | ----------- |
          | url | $(params.git-clone-url) |
          | commit | $(params.git-clone-commit) |

          ## Build Image
          | Name | Value |
          | ----------- | ----------- |
          | IMAGE_DIGEST | $(params.build-image-image-digest) |

          ## Deploy: DEV
          | Name          | Value |
          |---------------| ----------- |
          | Chart URL     | https://github.com/tekton-autogov/nodejs-example.git |
          | Chart Version | 0fb2dc73b141ef738429ea58a2dc9838d098d076 |
          | Deployed URL | http://nodejs-example-nodejs-example.apps.x8ccdonr.eastus.aroapp.io/ |
          EOF

