replicaCount: 1

image:
  pullPolicy: Always

service:
  name: nodejs-example
  type: ClusterIP
  port: 80
  targetport: 8080

probe:
  readypath: /
  livepath:  /

route:
  name: nodejs-example
  enabled: True
  annotations: {
  }
  path: /

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:   #  cpu: 100m
  #  memory: 128Mi
  # requests:   #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {
}

tolerations: []

affinity: {
}

pullSecret:
  enabled: False
  secretName: "pull-secret"
  secretKey: ".dockerconfigjson"

